Port to GUI UI library
iegomez/lds pull request #21
Opened 2020-07-02 17:08 UTC by scartill

- New library for UI
- Rearranged the GUI
- Bonus: natively works under Windows (tested with Windows 10)
- No logic changed (in theory)

2020-07-02 23:46 UTC, iegomez commented
Holy PRs, @scartill, that's a big one! 👏 

Let me check it out locally to confirm it build and runs nicely (I take it you're working on Windows, I do on Linux but also have a Mac machine for work), and go through the code, but kudos!

2020-07-03 00:30 UTC, iegomez requested changes
Just a quick feedback before I dive into it:

- In Mac it builds without issues but in Linux (Mint 19.3) I was missing the `xkbcommon-x11` package, so I had tun run this:
```
sudo apt-get install libxkbcommon-x11-0 libxkbcommon-x11-dev
```
- In both cases `tab` doesn't switch between inputs (maybe a `gioui` limitation?), and I'm also not able to select MQTT username nor password inputs manually.
- The layout looks pretty messy and condensed in both Mac and Linux. It may have to do with both machines having HiDPI displays, not sure at this moment. I'm attaching an image of running it on Mint, but it looked the same in Mac:

![Screenshot from 2020-07-02 20-29-26](https://user-images.githubusercontent.com/5600043/86419922-c855a000-bca2-11ea-8cc0-186f92d19e54.png)

2020-07-03 06:59 UTC, scartill commented
@iegomez, many thanks for taking a look!

Sorry for a huge PR, but that was the only consistent way 

* Yeah, that looks like a mess. That have to do with screen resolution, I believe. I've tested user the same Linux Mint with no trouble. Will try to play with resolution and see what happens.
* As for dependency, that is indeed derived from GIO UI, will add it to documentation.
* Tabs, I'm afraid, are GIO UI limitations, but that library is under heavy development - many things are upcoming.

For the reference, attaching the screenshot for Mint, pretty much the same is under Windows (no Mac to test on, sorry :)

![image](https://user-images.githubusercontent.com/1055918/86440698-99c3dd80-bd13-11ea-85e7-1d8de4a99765.png)

2020-07-03 22:12 UTC, iegomez commented
Ah, indeed that looks pretty nice, so probably it's the HiDPI scaling that's messing it.

One more thing: when we discussed it in the issue, I thought you were gonna add a separate GUI using `gio ui` instead of replacing the `dear imgui` one, but maybe I misunderstood. I'm open for discussion though: as I've mentioned on other occasions, I'm pretty tight with work and trying to get `mosquitto-go-auth` to 1.0, so it makes much more sense for you to be making the big decisions and me backing off a bit and just reviewing stuff.

2020-07-10 10:18 UTC, scartill commented
I've changed layout dimensions to device-independent pixel, which may fixed HiDP issue (in theory, cannot test, pardon), and made some minor layout changes.

I'm sorry if I've caused any misunderstanding with `dear imgui`, but as to keep it - that may be doable, but requires even more major overhaul. I'm not sure there is a need for dual interface.

2020-07-11 23:51 UTC, iegomez commented
It looks a bit better, input sizes and the console definitely saw a great improvement, so kudos!

Sadly, side buttons are still messed:
![Screenshot from 2020-07-11 19-46-59](https://user-images.githubusercontent.com/5600043/87235896-9681bf00-c3af-11ea-9a86-1e7b6bce8f93.png)

As for keeping `dear imgui` interface, don't worry: if I find the time I'll open a different branch with it, maybe see if the original issue is fixed or I can do anything about it, and then we can merge it to have both. We'll see. :wink:

2020-07-13 09:09 UTC, scartill commented
Made a change that would (probably :) fix the button panel.

2020-07-14 02:52 UTC, iegomez commented
Yesterday I messed my local machine with a bad Linux Mint upgrade, so today I reconfigured but I'm running into some issue trying to build:
```
Package wayland-egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `wayland-egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'wayland-egl' found
Package wayland-client was not found in the pkg-config search path.
Perhaps you should add the directory containing `wayland-client.pc'
to the PKG_CONFIG_PATH environment variable
No package 'wayland-client' found
Package wayland-cursor was not found in the pkg-config search path.
Perhaps you should add the directory containing `wayland-cursor.pc'
to the PKG_CONFIG_PATH environment variable
No package 'wayland-cursor' found
Package x11-xcb was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11-xcb.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11-xcb' found
```
So let me fix that and then I'll check it.

2020-07-14 15:11 UTC, iegomez commented
@scartill Just built it in the Mac and side buttons are looking good!

2020-07-14 16:01 UTC, scartill commented
That's great, thank you!

2020-07-21 14:02 UTC, scartill commented
Hi @iegomez,

Should I amend these changes further? What are your thoughts?

2020-07-21 14:06 UTC, iegomez commented
Hey @scartill!

Let me take a final look today after work and then you should be all set.

2020-07-22 02:05 UTC, iegomez requested changes
Mostly nitpicks about style, I don't know `gioui` to do a helpful review in that regard.

Also, could you add changes to the docs to build the app?

2020-07-22 02:05 UTC, iegomez commented on config.go
> +
Could you remove the empty line? It should also sort external imports.

2020-07-22 02:05 UTC, iegomez commented on config.go
> +	mwOpen       = true
What's the use for this? I see no other mentions in the project.

2020-07-22 02:05 UTC, iegomez commented on config.go
> +			MaxExecTime: 100,
This could be a a `defaultMaxExecTime` package constant.

2020-07-22 02:05 UTC, iegomez commented on config.go
> +		cMqtt := mqtt{}
I know this is my fault, but it'd be nice if we just throw all these declarations as literals in `config` assignment.

2020-07-22 02:05 UTC, iegomez commented on config.go
> +	}
Again, this is on me, but we could change it to:
```
log.SetLevel(log.InfoLevel)
if l, err := log.ParseLevel(config.LogLevel); err != nil {
    log.SetLevel(l)
}
```
Even better, we could have a `map[string]struct{}` with allowed levels, but that could be done later.

2020-07-22 02:05 UTC, iegomez commented on data.go
> +	c "strconv"
I'm not a fan of renaming packages unless there's name collisions, it makes it less explicit.

2020-07-22 02:05 UTC, iegomez commented on data.go
> +	l "gioui.org/layout"
Same as above, and please remove the trailing empty line to get imports sorted.

2020-07-22 02:05 UTC, iegomez commented on forwarder.go
Empty line here and other imports.

2020-07-22 02:05 UTC, iegomez commented on forwarder.go
> +	l "gioui.org/layout"
See comments above.

2020-07-22 02:05 UTC, iegomez commented on giox_helpers.go
> +	l "gioui.org/layout"
Once again.

2020-07-22 02:05 UTC, iegomez commented on lora.go
> +	l "gioui.org/layout"
Same old and empty lines.

2020-07-22 02:05 UTC, iegomez commented on mqtt.go
> +	l "gioui.org/layout"
:roll_eyes:

2020-07-22 02:05 UTC, iegomez commented on output.go
> +	l "gioui.org/layout"
:eyes:

2020-07-30 15:44 UTC, scartill commented
Hi @iegomez ,

I've tried to address all the issues, and updated the doc.

Regards,
Boris

2020-07-31 00:07 UTC, iegomez approved these changes

2020-07-31 00:08 UTC, iegomez commented
Looks good! :rocket:

2020-07-31 07:47 UTC, merged

2020-07-31 07:47 UTC, scartill commented
Merged, thank you!