Feat/packer forwarder
iegomez/lds pull request #7
Opened 2020-01-14 08:25 UTC by scartill

Added support for Semtech `packet forwarder` protocol to be used with a generic network server (not only chirpstack), which receives data via UDP. To the date, only unconfirmed uplinks are supported. UDP reception could be quite easily implemented as well, if needed by anyone.

BTW, thank you for a great tool.

2020-01-15 15:27 UTC, iegomez commented
Hi, @scartill, thanks for the PR! Let me take a look at it and I'll get back to you as soon as I can.

2020-01-31 15:17 UTC, iegomez requested changes

2020-01-31 15:17 UTC, iegomez commented on README.md
> +This program was also extended to generate raw PACKET FORWARDER UDP-based protocol as alternative transport, to be used with general LoRaWAN netfork server (e.g. [lorawan-server](https://github.com/g
There's a typo in `netfork`.

2020-01-31 15:17 UTC, iegomez commented on device.go
> +		var ulfc uint32 = 0
There's no need to assign `nil` to `err`. Also, prefer to declare `ulfc` like this:
```
var ulfc uint32
```

2020-01-31 15:17 UTC, iegomez commented on forwarder.go
> +		log.Warn("Bad Network server UDP port")
I think the message could be improved and prefer to start with a small case, something like this (just an example): network server UDP port must be a number.

2020-01-31 15:17 UTC, iegomez commented on forwarder.go
> +	log.Infoln("UDP Forwarder Started (MQTT disabled)")
Use lower case for started.

2020-01-31 15:17 UTC, iegomez commented on forwarder.go
> +	log.Infoln("UDP Forwarder Stopped (MQTT back again")
Same as above and you're missing a closing parenthesis.

2020-01-31 15:20 UTC, iegomez commented
Hey, @scartill, sorry for the delay. This looks good, just left some nitpick comments.
By the way, I'm not working with anything LoRa related since almost half a year now so I don't get to use or test this any more. Would you like to be added as a maintainer so the repo stays alive?

2020-02-11 10:19 UTC, scartill commented
Hello, @iegomez, sorry for a pause from my side. I fixed all the issues. I'm not sure that I will actively continue the development, but anyways I'll be glad to help, so add me to maintainers, please.

2020-02-11 14:17 UTC, merged